[build-system]
requires = ["cibuildwheel >= 2.3.0", "setuptools>=42", "wheel", "Cython", "numpy"]
build-backend = "setuptools.build_meta"

[[project]]
name = "grad_tts"
requires = ["Cython", "numpy"]
