# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: python-publish-pypi

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
       # os: [macos-11, macos-12, macos-13]
         os: [ubuntu-20.04, ubuntu-22.04, windows-2019, windows-2022, macos-latest]
    env:
      SYSTEM_VERSION_COMPAT: 0  
        # python-version: [3.8, 3.9, 3.10, 3.11]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install Cython numpy twine
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.13.1 Cython numpy
      # - name: Build wheels
      #   run: python -m cibuildwheel --output-dir wheelhouse
      - name: Build source distribution
        run: python setup.py sdist
      - name: Publish package
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload --skip-existing ./wheelhouse/*.whl
          twine upload --skip-existing ./dist/*
